name: build
on:
  push:
    paths-ignore:
      - "*.md"
jobs:
  build:
    runs-on: windows-latest
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Prepare
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          curl -OL https://github.com/upx/upx/releases/download/v5.0.0/upx-5.0.0-win64.zip
          7z e -y ./*.zip -o"."
          mkdir libs && cd libs
          curl -OL https://github.com/2ndlab/ANGLE.Static/releases/download/v2.0.0-pre/angle-x64-windows-static-chromium-7151-10.0.26100.0.7z
          curl -OL https://github.com/2ndlab/SkiaSharp.Static/releases/download/v2.0.0-pre/libHarfBuzzSharp-10.0.26100.0.7z
          curl -OL https://github.com/2ndlab/SkiaSharp.Static/releases/download/v2.0.0-pre/libSkiaSharp-2.88.9-10.0.26100.0.7z
          7z e -y angle-x64-windows-static-chromium-7151-10.0.26100.0.7z 
          7z e -y libHarfBuzzSharp-10.0.26100.0.7z
          7z e -y libSkiaSharp-2.88.9-10.0.26100.0.7z
          ls -al
          mv *.lib *.pdb ../Avalonia-NativeAOT-SingleFile/native/

      - name: Build
        working-directory: ${{github.workspace}}
        shell: pwsh
        run: |
          msbuild /m /t:restore Avalonia-NativeAOT-SingleFile.sln /p:Configuration=Release /p:Platform="Any CPU"
          dotnet publish Avalonia-NativeAOT-SingleFile\Avalonia-NativeAOT-SingleFile.csproj -r win-x64 -c Release
          mv Avalonia-NativeAOT-SingleFile\bin\x64\Release\net8.0-windows\win-x64\native\* .

      - name: Package
        working-directory: ${{github.workspace}}
        shell: pwsh
        run: |
          ./upx.exe --ultra-brute --overlay=strip .\Avalonia-NativeAOT-SingleFile.exe -o Avalonia-NativeAOT-SingleFile.UPX.exe
          7z a -y -mx9 Avalonia-NativeAOT-SingleFile.7z ./Avalonia-NativeAOT-SingleFile.exe ./Avalonia-NativeAOT-SingleFile.pdb
          7z a -y -mx9 Avalonia-NativeAOT-SingleFile.UPX.7z ./Avalonia-NativeAOT-SingleFile.UPX.exe

      - name: List dir
        working-directory: ${{github.workspace}}
        shell: bash
        run: ls -al .

      - uses: actions/upload-artifact@v4
        id: upload-artifact-1
        with:
          name: Avalonia-NativeAOT-SingleFile.7z
          path: Avalonia-NativeAOT-SingleFile.7z

      - uses: actions/upload-artifact@v4
        id: upload-artifact-2
        with:
          name: Avalonia-NativeAOT-SingleFile.UPX.7z
          path: Avalonia-NativeAOT-SingleFile.UPX.7z

      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: Avalonia-NativeAOT-SingleFile.7z
          subject-digest: sha256:${{ steps.upload-artifact-1.outputs.artifact-digest }}

      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: Avalonia-NativeAOT-SingleFile.UPX.7z
          subject-digest: sha256:${{ steps.upload-artifact-2.outputs.artifact-digest }}

      - name: Release artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Avalonia-NativeAOT-SingleFile.7z
            Avalonia-NativeAOT-SingleFile.UPX.7z
