name: build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          
      - name: Prepare
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
            wget https://github.com/upx/upx/releases/download/v5.0.0/upx-5.0.0-win64.zip
            7z x ./*.zip
            mkdir libs && cd libs
            wget https://github.com/2ndlab/ANGLE.Static/releases/download/v1.2.0/av_libglesv2-10.0.26100.0.7z
            wget https://github.com/2ndlab/SkiaSharp.Static/releases/download/v1.1.0/libHarfBuzzSharp-10.0.26100.0.7z
            wget https://github.com/2ndlab/SkiaSharp.Static/releases/download/v1.1.0/libSkiaSharp-2.88.9-10.0.26100.0.7z
            7z x ./*.7z 
            rm -rf ./*.7z
            mv ./ ../Avalonia-NativeAOT-SingleFile/native/

      - name: Build
        working-directory: ${{github.workspace}}
        shell: pwsh
        run: |
            dotnet restore
            dotnet publish -r win-x64 -c Release
            mv Avalonia-NativeAOT-SingleFile\Avalonia-NativeAOT-SingleFile\bin\Release\net8.0-windows\win-x64\native\ .

      - name: Package ANGLE
        working-directory: ${{github.workspace}}
        shell: pwsh
        run: |
            # ./upx.exe --ultra-brute --overlay=strip .\Avalonia-NativeAOT-SingleFile.exe -o Avalonia-NativeAOT-SingleFile.UPX.exe
            7z a -y -mx9 Avalonia-NativeAOT-SingleFile.7z ./Avalonia-NativeAOT-SingleFile.*

      - name: Create MD5
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          md5sum Avalonia-NativeAOT-SingleFile.7z > Avalonia-NativeAOT-SingleFile.7z.md5

      - name: List dir
        working-directory: ${{github.workspace}}
        shell: bash
        run: ls -al .

      - uses: actions/upload-artifact@v4
        with:
          name: Avalonia-NativeAOT-SingleFile.7z
          path: Avalonia-NativeAOT-SingleFile.7z

      - uses: actions/upload-artifact@v4
        with:
          name: Avalonia-NativeAOT-SingleFile.7z.md5
          path: Avalonia-NativeAOT-SingleFile.7z.md5

      - name: Release artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Avalonia-NativeAOT-SingleFile.7z
            Avalonia-NativeAOT-SingleFile.7z.md5
